print("----------")
print("Calculator")
print("----------")
print("x=?")
x = input()
print("y=?")
y = input()
Plus = int(x)+int(y)
minute = int(x)-int(y)
Multiplacation = int(x)*int(y)
Devide = int(x)/int(y)
print("x+y","=",Plus)
print("x-y","=",minute)
print("x*y","=",Multiplacation)
print("x/y","=",Devide)
